spring:
  application:
    name: ming-ai-code-backend
  session:
    store-type: redis
    # session 30 天过期
    timeout: 2592000
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ming_ai_code
    username: root
    password: 1234
  profiles:
    active: local
server:
  port: 8123
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.ming.mingaicode.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

